### ISSUE TITLE
Support micro-batching in BentoML SageMaker deployment

### ISSUE THREAD

**Issue by parano** [bentoml/aws-sagemaker-deploy#1]
**Is your feature request related to a problem? Please describe.**

Currently, BentoML deployment on SageMaker does not utilize the micro-batching capability: https://github.com/bentoml/BentoML/blob/master/bentoml/deployment/sagemaker/sagemaker_serve.py

**Describe the solution you'd like**
Needs investigation

**Describe alternatives you've considered**
SageMaker expects a WSGI app and we may need to add a WSGI wrapper to the bentoML Marshal Server.

**Additional context**
n/a

**Comment by parano** [comment]
We will revisit this issue after 1.0 release, which will make supporting micro-batching in SageMaker deployment possible

**Comment by cliu0507** [comment]
@parano @jjmachan 
Not sure if it is the right place to ask:

Wanna confirm my understanding is correct:
Did you mean current aws sagemaker deployment through bentoML can NOT support adaptive micro batching mechanism yet? (batch size always equals 1 ?)

Also, for AWS lambda deployment, does it the same limitation? 

Thanks!

**Comment by jjmachan** [comment]
hey @cliu0507 sadly you are right, the current version of sagemaker deployment and lambda deployment does not support micro batching mechanism. But we are looking to add support for this with the bentoml 1.0 release 🤞🏽

**Comment by yubozhao** [comment]
implemented
