### ISSUE TITLE
incorrect Content-Type header casing in created lambda

### ISSUE THREAD

**Issue by yochail** [bentoml/aws-sagemaker-deploy#41]
When deploying with terraform:
``` sh
terraform apply -var-file=bentoctl.tfvars -auto-approve
```
An aws lambda is created with the following code:
[see source](https://github.com/bentoml/aws-sagemaker-deploy/blob/797d0911f7cd56103f6657891eb9f4b81301292b/bentoctl_sagemaker/templates/terraform_default.tf#L154)
``` python
        sagemaker_response = runtime.invoke_endpoint(
            EndpointName=\"newstory-demo-endpoint\",
            ContentType=safeget(event, 'headers', 'content-type', default='application/json'),
            CustomAttributes=safeget(event, 'path', default='')[1:],
            Body=b64decode(event.get('body')) if event.get('isBase64Encoded') else event.get('body')
        )
```
for every content type that is not 'application/json', this will not work, since the header name should be ["Content-Type"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) and not 'content-type' (casing is different). (that is also the name that will be given to this header using a standard library, e.g python's requests lib
this should be fixed by normalizing the keys casing inside 'safeget' function or by changing the 'content-type' key to 'Content-Type'

**Comment by jjmachan** [comment]
@yochail Thank you so much for spotting this and proposing the fix. I've added the fix and we will be releasing this on Monday.

Thanks again 🤗
