### ISSUE TITLE
Dockerfile doesn't load nginx or /health endpoint

### ISSUE THREAD

**Issue by eob** [bentoml/aws-sagemaker-deploy#7]
Thanks for this project!

As best as I can tell, when I follow the instructions, the resulting docker ENTRYPOINT and CMD still seem to be the same as the a non-SageMaker container -- none of the `nginx`, `wsgi`, etc files are being loaded. Instead, it runs:

```
./docker-entrypoint.sh bentoml serve-gunicorn /bento
```

I'm fairly certain it is supposed to run `./serve` instead so that NGINX loads.

The result is the sagemaker hangs forever waiting for the `/health` endpoint (which isn't there).

Here is the Dockerfile this code generates for me:

```
FROM bentoml/model-server:0.12.1-py38

# the env var $PORT is required by heroku container runtime
ENV PORT 8080
EXPOSE $PORT

RUN apt-get update --fix-missing &&     apt-get install -y nginx &&     apt-get clean

# gevent required by AWS Sagemaker
RUN pip install gevent>=20.9.0

# copy over model files
COPY . /bento
WORKDIR /bento

RUN if [ -f /bento/bentoml-init.sh ]; then bash -c /bento/bentoml-init.sh; fi

ENV PATH="/bento:$PATH"
```

Is there supposed to be code in there that starts the nginx service instead? (Or Yatai service?)

**Comment by jjmachan** [comment]
yep your right. the `serve` script is what is starting up nginx and the health endpoint. According to sagemaker's specs for inference containers (https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html) sagemaker itself will run `docker run image serve` and that is how the serve script get running and we load nginx and /ping and /invocations 

Are you using the latest version of the deploy script (this repo)?
